name: Deploy to Firebase Hosting on push to main
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # or whichever version you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm ci  # Use `npm ci` to install dependencies from package-lock.json

      # Step 4: Build Next.js app
      - name: Build Next.js app
        run: |
          npm run build  # Builds your Next.js app (makes .next folder)

      # Step 6: Deploy to Firebase
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIRECARD }}  # Your Firebase service account key (see step below)
          channelId: live  # The deployment channel (live for production, staging for a staging environment)
          projectId: firecard  # Your Firebase project ID
